// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using rise_gs;

#nullable disable

namespace rise_gs.Migrations
{
    [DbContext(typeof(RiseContext))]
    [Migration("20251119021254_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("rise_gs.Models.BemEstar", b =>
                {
                    b.Property<int>("IdBemEstar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_BEM_ESTAR");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBemEstar"));

                    b.Property<string>("DescAtividade")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("DESC_ATIVIDADE");

                    b.Property<DateTime>("DtRegistro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_REGISTRO");

                    b.Property<TimeSpan?>("HorasEstudo")
                        .HasColumnType("INTERVAL DAY(8) TO SECOND(7)")
                        .HasColumnName("HORAS_ESTUDO");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<int>("NivelHumor")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NIVEL_HUMOR");

                    b.HasKey("IdBemEstar")
                        .HasName("PK_RISE_BEM_ESTAR");

                    b.HasIndex("IdUsuario");

                    b.ToTable("TB_RISE_BEM_ESTAR", (string)null);
                });

            modelBuilder.Entity("rise_gs.Models.Curriculo", b =>
                {
                    b.Property<int>("IdCurriculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CURRICULO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCurriculo"));

                    b.Property<string>("ExperienciaProfissional")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("EXPERIENCIA_PROFISSIONAL");

                    b.Property<string>("Formacao")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("FORMACAO");

                    b.Property<string>("Habilidades")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("HABILIDADES");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("Links")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("LINKS");

                    b.Property<string>("Projetos")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("PROJETOS");

                    b.Property<string>("TituloCurriculo")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TITULO_CURRICULO");

                    b.Property<DateTime?>("UltimaAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ULTIMA_ATUALIZACAO");

                    b.HasKey("IdCurriculo")
                        .HasName("PK_RISE_CURRICULO");

                    b.HasIndex("IdUsuario");

                    b.ToTable("TB_RISE_CURRICULO", (string)null);
                });

            modelBuilder.Entity("rise_gs.Models.Curso", b =>
                {
                    b.Property<int>("IdCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CURSO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCurso"));

                    b.Property<string>("AreaCurso")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("AREA_CURSO");

                    b.Property<string>("DescCurso")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESC_CURSO");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("LinkCurso")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("LINK_CURSO");

                    b.Property<string>("NomeCurso")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("NOME_CURSO");

                    b.HasKey("IdCurso")
                        .HasName("PK_RISE_CURSO");

                    b.HasIndex("IdUsuario");

                    b.ToTable("TB_RISE_CURSO", (string)null);
                });

            modelBuilder.Entity("rise_gs.Models.TrilhaObjetivo", b =>
                {
                    b.Property<int>("IdObjetivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_OBJETIVO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdObjetivo"));

                    b.Property<string>("CategoriaObjetivo")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("CATEGORIA_OBJETIVO");

                    b.Property<string>("Concluido")
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("CONCLUIDO");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CONCLUSAO");

                    b.Property<DateTime?>("DataPlanejada")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_PLANEJADA");

                    b.Property<DateTime?>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<int>("IdTrilha")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TRILHA");

                    b.Property<string>("TituloObjetivo")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("TITULO_OBJETIVO");

                    b.HasKey("IdObjetivo")
                        .HasName("PK_TRILHA_OBJETIVO");

                    b.HasIndex("IdTrilha");

                    b.ToTable("TB_RISE_TRILHA_OBJETIVO", (string)null);
                });

            modelBuilder.Entity("rise_gs.Models.TrilhaProgresso", b =>
                {
                    b.Property<int>("IdTrilha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TRILHA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTrilha"));

                    b.Property<string>("CategoriaTrilha")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("CATEGORIA_TRILHA");

                    b.Property<DateTime?>("DataPlanejada")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_PLANEJADA");

                    b.Property<DateTime?>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<DateTime?>("DtInicio")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_INICIO");

                    b.Property<DateTime?>("DtUltimaAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ULTIMA_ATUALIZACAO");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<int?>("PercentualConcluido")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PERCENTUAL_CONCLUIDO");

                    b.Property<string>("TituloTrilha")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("TITULO_TRILHA");

                    b.HasKey("IdTrilha")
                        .HasName("PK_TRILHA_PROGResso");

                    b.HasIndex("IdUsuario");

                    b.ToTable("TB_RISE_TRILHA_PROGRESSO", (string)null);
                });

            modelBuilder.Entity("rise_gs.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESC");

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("EMAIL_USUARIO");

                    b.Property<string>("Habilidades")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("HABILIDADES");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("NOME__USUARIO");

                    b.Property<string>("SenhaUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("SENHA_USUARIO");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TELEFONE");

                    b.Property<string>("TipoUsuario")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TIPO_USUARIO");

                    b.HasKey("IdUsuario")
                        .HasName("PK_RISE_USUARIO");

                    b.ToTable("TB_RISE_USUARIO", (string)null);
                });

            modelBuilder.Entity("rise_gs.Models.BemEstar", b =>
                {
                    b.HasOne("rise_gs.Models.Usuario", "Usuario")
                        .WithMany("RegistrosBemEstar")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BEM_ESTAr_USUARIO");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("rise_gs.Models.Curriculo", b =>
                {
                    b.HasOne("rise_gs.Models.Usuario", "Usuario")
                        .WithMany("Curriculos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CURRICULO_USUARIO");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("rise_gs.Models.Curso", b =>
                {
                    b.HasOne("rise_gs.Models.Usuario", "Usuario")
                        .WithMany("Cursos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CURSO_USUARIO");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("rise_gs.Models.TrilhaObjetivo", b =>
                {
                    b.HasOne("rise_gs.Models.TrilhaProgresso", "Trilha")
                        .WithMany("Objetivos")
                        .HasForeignKey("IdTrilha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OBJETIVO_TRILHA");

                    b.Navigation("Trilha");
                });

            modelBuilder.Entity("rise_gs.Models.TrilhaProgresso", b =>
                {
                    b.HasOne("rise_gs.Models.Usuario", "Usuario")
                        .WithMany("Trilhas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TRILHA_USUARIO");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("rise_gs.Models.TrilhaProgresso", b =>
                {
                    b.Navigation("Objetivos");
                });

            modelBuilder.Entity("rise_gs.Models.Usuario", b =>
                {
                    b.Navigation("Curriculos");

                    b.Navigation("Cursos");

                    b.Navigation("RegistrosBemEstar");

                    b.Navigation("Trilhas");
                });
#pragma warning restore 612, 618
        }
    }
}
