// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using rise_gs;

#nullable disable

namespace rise_gs.Migrations
{
    [DbContext(typeof(RiseContext))]
    [Migration("20251114152644_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("rise_gs.Models.BemEstar", b =>
                {
                    b.Property<int>("IdBemEstar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID__BEM_ESTAR");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBemEstar"));

                    b.Property<string>("DescAtividade")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("DESC_ATIVIDADE");

                    b.Property<DateTime>("DtRegistro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_REGISTRO");

                    b.Property<TimeSpan?>("HorasEstudo")
                        .HasColumnType("INTERVAL DAY(8) TO SECOND(7)")
                        .HasColumnName("HORAS_ESTUDO");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<int>("NivelHumor")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NIVEL_HUMOR");

                    b.HasKey("IdBemEstar")
                        .HasName("PK_RISE_BEM_ESTAR");

                    b.HasIndex("IdUsuario");

                    b.ToTable("TB_RISE_BEM_ESTAR", (string)null);
                });

            modelBuilder.Entity("rise_gs.Models.Curriculo", b =>
                {
                    b.Property<int>("IdCurriculo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CURRICULO");

                    b.Property<string>("Habilidades")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("HABILIDADES");

                    b.Property<string>("ExperienciaProfissional")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("EXPERIENCIA_PROFISSIONAL");

                    b.Property<string>("Formacao")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("FORMACAO");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("Links")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("LINKS");

                    b.Property<string>("Projetos")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("PROJETOS");

                    b.Property<string>("TituloCurriculo")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TITULO_CURRICULO");

                    b.Property<DateTime?>("UltimaAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ULTIMA_ATUALIZACAO");

                    b.HasKey("IdCurriculo", "Habilidades")
                        .HasName("PK_RISE_CURRICULO");

                    b.HasIndex("IdUsuario");

                    b.ToTable("TB_RISE_CURRICULO", (string)null);
                });

            modelBuilder.Entity("rise_gs.Models.Curso", b =>
                {
                    b.Property<int>("IdCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CURSO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCurso"));

                    b.Property<string>("AreaCurso")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("AREA_CURSO");

                    b.Property<string>("DescCurso")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("DESC_CURSO");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("LinkCurso")
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("LINK_CURSO");

                    b.Property<string>("NomeCurso")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NOME_CURSO");

                    b.HasKey("IdCurso")
                        .HasName("PK_RISE_CURSO");

                    b.HasIndex("IdUsuario");

                    b.ToTable("TB_RISE_CURSO", (string)null);
                });

            modelBuilder.Entity("rise_gs.Models.TrilhaProgresso", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<DateTime?>("DtInicio")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_INICIO");

                    b.Property<DateTime?>("DtUltimaAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ULTIMA_ATUALIZACAO");

                    b.Property<int?>("PercentualConcluido")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PERCENTUAL_CONCLUIDO");

                    b.HasKey("IdUsuario")
                        .HasName("PK_RISE_TRILHA_PROGRESSO");

                    b.ToTable("TB_RISE_TRILHA_PROGRESSO", (string)null);
                });

            modelBuilder.Entity("rise_gs.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("EMAIL_USUARIO");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NOME__USUARIO");

                    b.Property<string>("SenhaUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("SENHA_USUARIO");

                    b.Property<string>("TipoUsuario")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TIPO_USUARIO");

                    b.HasKey("IdUsuario")
                        .HasName("PK_RISE_USUARIO");

                    b.ToTable("TB_RISE_USUARIO", (string)null);
                });

            modelBuilder.Entity("rise_gs.Models.BemEstar", b =>
                {
                    b.HasOne("rise_gs.Models.Usuario", "Usuario")
                        .WithMany("RegistrosBemEstar")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RISE_BEM_ESTAR_USUARIO");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("rise_gs.Models.Curriculo", b =>
                {
                    b.HasOne("rise_gs.Models.Usuario", "Usuario")
                        .WithMany("Curriculos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RISE_CURRICULO_USUARIO");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("rise_gs.Models.Curso", b =>
                {
                    b.HasOne("rise_gs.Models.Usuario", "Usuario")
                        .WithMany("Cursos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RISE_CURSO_USUARIO");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("rise_gs.Models.TrilhaProgresso", b =>
                {
                    b.HasOne("rise_gs.Models.Usuario", "Usuario")
                        .WithOne("TrilhaProgresso")
                        .HasForeignKey("rise_gs.Models.TrilhaProgresso", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RISE_PROGRESSO_USUARIO");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("rise_gs.Models.Usuario", b =>
                {
                    b.Navigation("Curriculos");

                    b.Navigation("Cursos");

                    b.Navigation("RegistrosBemEstar");

                    b.Navigation("TrilhaProgresso");
                });
#pragma warning restore 612, 618
        }
    }
}
